### ISSUE TITLE
Multiple stream support

### ISSUE THREAD

**Issue by NaanProphet** [sallar/mac-local-rtmp-server#1]
This is a really cool app! Thanks for sharing this.

Are multiple streams possible? I was wondering if I'd be able to ingest multiple cameras.

**Comment by sallar** [comment]
Thanks @naanprophet. Yes it is possible just use different keys and they will all stream :)

**Comment by NaanProphet** [comment]
Ah, thanks! Silly me, didn't realize the Streams window scrolled down. 🎥 

Mind if I make some tweaks to the README and make a pull request?

**Comment by sallar** [comment]
@naanprophet I would appreciate that 😊 thanks!

**Comment by Tmuat** [comment]
Hi Guys,

Very likely me being stupid but what do you mean by "Streams window scrolled down". I can't seem to find any way to add additional streams?

Cheers
<img width="406" alt="Screenshot 2019-08-13 at 18 26 22" src="https://user-images.githubusercontent.com/54077365/62962931-dc2cb500-bdf7-11e9-9b59-f3c4cab17dd8.png">

**Comment by NaanProphet** [comment]
@Tmuat by that I just meant that you can use your mouse wheel to scroll inside that window. Or you can reveal the scroll bar by bring the mouse to the right edge of the window

**Comment by Tmuat** [comment]
Hi Guys,

The issue I seem to be having is I cannot scroll or find the scroll bar on the edge of that window?

Cheers,
Tom

**Comment by PedroAnibarro1** [comment]
Hi! Thanks for making this awesome tool! I can't seem to scroll the window popup either. Have tried by scrolling on the track pad and even tried to resize the window to see if it showed up. Nothing.

**Comment by bjornsyse** [comment]
> Hi Guys,
> 
> The issue I seem to be having is I cannot scroll or find the scroll bar on the edge of that window?
> 
> Cheers,
> Tom

I have the exact same problem. I'm on a macbook. Do I need an external mouse or something? I sure can scroll anywhere in this window.

**Comment by sallar** [comment]
You would only be able to scroll if there are more than 1 streams currently going on. In the screenshot above nothing is being streamed so no scrolling

**Comment by bjornsyse** [comment]
How can I add a second stream then? I'm not even able to edit the key-field? Do I make two devices point to the same stream/key and they will be separated automatically?

**Comment by sallar** [comment]
@bjornsyse just use a different key. the URL should be the same but the key can be anything that you want. the random string displayed in the app is just a that.. a random string for you to copy. but you can enter anything you like

**Comment by bjornsyse** [comment]
Hi, yes that sounds great. I get the theory, but the problem is that these fields are greyed out/ghosted. They can't be edited?

**Comment by meistermoli** [comment]
> Hi, yes that sounds great. I get the theory, but the problem is that these fields are greyed out/ghosted. They can't be edited? (I'm on Catalina 10.15.4)
> 
> Any permissions missing? Don't understand what's wrong there.

To change the stream key just change it in the encoder setting.

@Sallar: love your app! Thanks a lot!

**Comment by sallar** [comment]
@bjornsyse as @meistermoli mentioned, you need to put those in your encoder (eg. OBS, etc). The only thing that you need from this app is the url which you can copy from the main window. There is a video guide in the README which you can follow too

**Comment by bjornsyse** [comment]
Thank you, NOW I get it. I write whatever key I want in the content source that is streaming and then your app will accept that as a key. I thought the whole time I had to declare or establish a certain key name in the app first. My bad, thanks for clearing that out! Video helped.
