### ISSUE TITLE
Multiple Streams. Scrolling. Change name of Key?

### ISSUE THREAD

**Issue by bjornsyse** [sallar/mac-local-rtmp-server#17]
Hi?

From reading the instructions I get the feeling I should be able to edit the name of the key and also create multiple stream servers (by scrolling?) I'm not sure how I do that. I've tried scrolling in the little window, also changing name of the stream does not seem to work, it's locked/ghosted. What am I doing wrong?

![image](https://user-images.githubusercontent.com/26255606/81065387-a5de1b00-8edb-11ea-806c-6ba1a0a220e5.png)

Regards Björn

**Comment by BenAndDevelopment** [comment]
Hey, 
Thanks for your question. That gave me the right leed. The "random" number, the stream key, just use what ever you want. This program just reacts to everything, and if you have multiple clients streaming to diffents keys, the app shows multiple streams by just scrolling.

**Comment by bjornsyse** [comment]
Thames, i figured it out finally. Program was smarter than I expected! 🙂

**Comment by franzuu** [comment]
> Thames, i figured it out finally. Program was smarter than I expected! 🙂

Hi! How were you able to change the url and stream key to something custom? It seems locked on my system also.

**Comment by bjornsyse** [comment]
I changed it not in the program itself but on the streaming end. So in my case, I made it up in the gopro app and the program accepted it.
