### ISSUE TITLE
Window is empty

### ISSUE THREAD

**Issue by ProjectDent** [sallar/mac-local-rtmp-server#3]
<img width="455" alt="screen shot 2018-08-11 at 09 12 07" src="https://user-images.githubusercontent.com/1865635/43989680-b39feb0c-9d46-11e8-91d8-fd72c9213cab.png">

macOS High Sierra, 10.13.5

**Comment by sallar** [comment]
Thanks @ProjectDent this is caused by the port 8000 being busy on your computer. I'm working on a fix ASAP.

**Comment by sallar** [comment]
@ProjectDent done :)

https://github.com/sallar/mac-local-rtmp-server/releases/tag/v1.2.0
