### ISSUE TITLE
Getting random Unicode characters in stream path once a camera stream connects

### ISSUE THREAD

**Issue by mmalliaparfitt** [sallar/mac-local-rtmp-server#5]
Hi Team,
9 times out of 10 i get random extra unicode characters after the address once the client connects: for example rtmp://127.0.0.1/live/B1W2Cbs8XI�: or rtmp://127.0.0.1/live/B1W2Cbs8Xs22
But it should be rtmp://127.0.0.1/live/B1W2Cbs8X according to your examples.
I am also not able to create my own stream key as you can in your example
I can connect to the above using VLC, but other non unicode apps fail to connect - i am running the latest version which i cloned today
any ideas please
Many thanks
Max
![screenshot 2018-08-22 17 53 25](https://user-images.githubusercontent.com/42617569/44478083-7a969800-a634-11e8-974b-1f3f4b591946.png)
![screenshot 2018-08-22 17 55 20](https://user-images.githubusercontent.com/42617569/44478110-900bc200-a634-11e8-94c8-eabf12c56f28.png)

**Comment by sallar** [comment]
Thanks @mmalliaparfitt I will look into the character thingie! However you should be able to just ignore that and use your own string since this is just a random string that is generated. What is the issue with you for example using your name as key?

**Comment by mmalliaparfitt** [comment]
Hi @sallar If i try connecting a stream with my own stream key, the camera shows it is connected, but the server never shows a connection, it just shows "No Live Streams Currently". Any thoughts

**Comment by mmalliaparfitt** [comment]
additional, the icon on the top bar does go red when i connect a stream, but the ui says no connections

**Comment by Thiagobhmg** [comment]
I can not do it either. including sending multiple cameras I needed to duplicate the app. but only one icon turns red indicating online. could explain better how to add multiple streams? it may seem easy to perform for which you have developed the application but it is not easy to understand for who is user.

**Comment by sallar** [comment]
This should be fixed in the latest version.
