### ISSUE TITLE
No Live Streams While ffmpeg is streaming live

### ISSUE THREAD

**Issue by unformatt** [sallar/mac-local-rtmp-server#9]
![image](https://user-images.githubusercontent.com/157132/48730896-aca2a080-ec09-11e8-8bfc-4b8ecda58f70.png)

`ffmpeg -f lavfi  -i testsrc -s 320x240 -ar 11025 -f flv -r 30.0 "rtmp://localhost"`

![image](http://g.recordit.co/kesIh2caNv.gif)

If I close your app, then ffmpeg errors - so I know that ffmpeg is connecting to your app but maybe I'm not specifying the rtmp URL correctly?

**Comment by sallar** [comment]
@unformatt yes you are specifying it incorrectly. it has to be: "`rtmp://localhost/live/STREAM_KEY_HERE`"

**Comment by unformatt** [comment]
@sallar Thanks for very fast response! I'm still seeing the same problem:

```
ffmpeg -f lavfi -i testsrc -s 320x240 -ar 11025 -f flv -r 30.0 "rtmp://localhost/live/HynOGqgCm"
```

![image](https://user-images.githubusercontent.com/157132/48732027-816d8080-ec0c-11e8-91d5-720ded83f7ad.png)

**Comment by sallar** [comment]
@unformatt hmmm Im not sure but it seems like that the ffmpeg flags are not correct because now the URL should be. Are you trying to stream from a video source to the URL using ffmpeg?

**Comment by unformatt** [comment]
Yes, trying to generate a test stream with ffmpeg for development. `-i testsrc` should creating a stream that looks something like

![image](https://user-images.githubusercontent.com/157132/48732303-43bd2780-ec0d-11e8-80c7-b774d433674c.png)

**Comment by sallar** [comment]
@unformatt Unfortunately I have very little experience with `ffmpeg` when it comes to streaming. I'll research this a bit...

**Comment by sallar** [comment]
@unformatt this is fixed in the latest version :) https://github.com/sallar/mac-local-rtmp-server/releases/tag/v1.3.0
